version: '3'

services:

  customer-service:
    build:
      context: ./../customer
      dockerfile: ./../customer/customer.dockerfile
    restart: always
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 1